//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Private_Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Med_Card
    {
        public int Note_ID { get; set; }
        public System.DateTime Note_date { get; set; }
        public string Diagnose { get; set; }
        public string Note { get; set; }
        public int Pacient_ID { get; set; }
        public int Doctor_ID { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Pacient Pacient { get; set; }
    }
}
