//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Private_Hospital
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testDbContext : DbContext
    {
        public testDbContext()
            : base("name=testDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointment { get; set; }
        public virtual DbSet<Direction> Direction { get; set; }
        public virtual DbSet<Doctor> Doctor { get; set; }
        public virtual DbSet<Med_Card> Med_Card { get; set; }
        public virtual DbSet<Pacient> Pacient { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
    }
}
